name: 'build'

on:
   workflow_dispatch:
   schedule:
    - cron: "59 02 * * *"
   push:
    branches:
      - "*"

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Set env vars"
        run: |
          # TIPS!! Works as an export replacement, that handles GITHUB_ENV
          export_ga() {
            for _name in "${@}"
            do
              local _key="${_name%%=*}"
              local _value="${_name#*=}"
              [ "${_key}" == "${_name}" ] && _value="${!_name}"
              export $_key="${_value}"
              echo "${_key}=${_value}" >> "${GITHUB_ENV}"
            done
          }
          
          export_ga GITHUB_SHA_SHORT="$(git rev-parse --short HEAD)"

          export_ga GH_REGISTRY="ghcr.io"
          export_ga GH_USER="${{ github.actor }}"
          export_ga GH_OWNER="${{ github.repository_owner }}"
          export_ga REPO_NAME="${{ github.event.repository.name }}"
          
          export_ga GH_IMAGE_NAME="${GH_REGISTRY}/${GH_OWNER}/${REPO_NAME}"

          export_ga BUILD_DATE="$(TZ=Europe/Paris date -Iseconds)"

      - name: 'Login to github container registry'
        uses: "docker/login-action@v2.1.0"
        with:
          registry: "${{ env.GH_REGISTRY }}"
          username: "${{ env.GH_USER }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Build image builder"
        uses: docker/build-push-action@v4
        with:
          push: false
          no-cache: true
          tags: builder:latest

      - name: "Set VERSION as env"
        run: |
          echo "VERSION=$(docker run --rm=true -i builder:latest --version)" >> "${GITHUB_ENV}"

      - name: "Build image youtube-dlp ${{ env.GITHUB_SHA_SHORT }} (for version ${{ env.VERSION }})"
        uses: docker/build-push-action@v4
        with:
          push: true
          no-cache: true
          file: "Dockerfile-version"
          build-args: |
            VCS_REF=${{ env.GITHUB_SHA_SHORT }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            VERSION=${{ env.VERSION }}
          tags: "${{ env.GH_IMAGE_NAME }}:${{env.GITHUB_SHA_SHORT}},${{ env.GH_IMAGE_NAME }}:${{ env.VERSION }},${{ env.GH_IMAGE_NAME }}:${{ env.VERSION }}-${{ env.GITHUB_SHA_SHORT }},${{ env.GH_IMAGE_NAME }}:latest"

